name: Linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: yarn

      - name: Install yarn
        run: npm install -g yarn
      - name: Install modules
        run: yarn
      - name: Build production
        run: yarn build:prod
      - name: Typescript linting
        run: yarn lint
      - name: CSS linting
        run: yarn stylelint
      - name: Unit testing
        run: yarn test:unit